language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: deps=no
    - php: 7
      env: deps=no


cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - composer self-update
  - if [ "$deps" = "no" ]; then composer --prefer-dist install; fi;


script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
  - ./vendor/bin/phpcs --standard=MEQP1 --ignore=vendor .

after_success: